const countries = {
    "ar-SA": "Arabic",
    "bn-IN": "Bengali",
    "bs-BA": "Bosnian",
    "ca-ES": "Catalan",
    "da-DK": "Danish",
    "de-DE": "German",
    "en-US": "English",
    "fr-FR": "french",
    "fi-FI": "finnish",
    "gu-IN": "Gujarati",
    "gl-ES": "Galician",
    "he-IL": "Hebrew",
    "hi-IN": "Hindi",
    "it-IT": "Italian",
    "id-ID": "Indonesian",
    "ja-JP": "Japanese",
    "ko-KR": "Korean",
    "la-LA": "Lao",
    "mt-MT": "Maltese",
    "ne-NP": "Nepali",
    "sn-ZW": "Shona",
    "so-SO": "Somali",
    "sq-AL": "Albanian",
    "te-IN": "Telugu",
    "ta-LK": "Tamil",
    "uk-UA": "Ukrainnian",
    "vi-VN": "Vietnamese",
    "wo-SN": "Wolof",
    "xh-ZA": "Xhosa",
    "yi-YD": "Yiddish",
    "uz-ZA": "Zulu",

}